---

- name: Install utility packages
  package:
    name: '{{ item }}'
    state: 'present'
    update_cache: true
  become: true
  with_items:
    - curl
    - jq

- name: Copy unseal script
  template:
    dest: "{{ vault_config_path }}/vault-unseal.sh"
    src: "vault-unseal.sh.j2"
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    mode: 0744
  become: true

- name: Create the Vault unseal service systemd config
  template:
    src: vault-unseal.service.j2
    dest: "/etc/systemd/system/vault-unseal.service"
    owner: "root"
    group: "root"
    mode: 0644
  become: true
  notify:
    - Reload vault-unseal systemd

- name: Ensure vault-unseal is started at boot
  service:
    name: vault-unseal
    enabled: true
  become: true
