---

- name: Check if vault is sealed
  uri:
    url: "{{ vault_api_dns_url }}/v1/sys/health"
    validate_certs: "{{ tls_skip_verify | ternary('false', 'true') }}"
    status_code: 200,429,472,501,503
  register: vault_health_response
  run_once: true

- name: Unseal vault
  uri:
    url: "{{ vault_api_dns_url }}/v1/sys/unseal"
    body:
      key: "{{ item }}"
    body_format: json
    method: PUT
    validate_certs: "{{ tls_skip_verify | ternary('false', 'true') }}"
  register: unseal_vault_response
  no_log: true
  run_once: true
  with_items:
    - "{{ vault_keys }}"
  when:
    - vault_health_response.status == 503
    - vault_health_response.status != 501
    - vault_keys is defined
