---
- name: Converge
  hosts: all
  become: true
  gather_facts: true
  environment:
    http_proxy: "http://10.201.0.1:4567"
    https_proxy: "http://10.201.0.1:4567"
  vars:
    server_hostname: vault.ricsanfre.com
    ssl_key_size: 4096
    key_type: RSA
    country_name: ES
    email_address: admin@ricsanfre.com
    organization_name: Ricsanfre
    ansible_user: root

  pre_tasks:
    - name: Generate custom CA
      include_tasks: tasks/generate_custom_ca.yml
      args:
        apply:
          delegate_to: localhost
          become: false
    - name: Generate customCA-signed SSL certificates for minio
      include_tasks: tasks/generate_ca_signed_cert.yml
      args:
        apply:
          delegate_to: localhost
          become: false

    - name: Load tls key and cert
      set_fact:
        vault_key: "{{ lookup('file', 'certificates/' + server_hostname + '.key') }}"
        vault_cert: "{{ lookup('file', 'certificates/' + server_hostname + '.pem') }}"
        vault_ca: "{{ lookup('file', 'certificates/CA.pem') }}"

  roles:
    - role: ricsanfre.vault
      vault_enable_tls: true
      custom_ca: true
      vault_listener_localhost_enable: true

  tasks:

    - name: Insert http(s) export in dotfile
      become: true
      lineinfile:
        path: ~{{ ansible_user }}/.bashrc
        regexp: "^export VAULT_ADDR="
        line: "export VAULT_ADDR='https://vault.ricsanfre.com:8200'"
        owner: "{{ ansible_user }}"
        create: true
        mode: 0644

    - name: Insert CA cert export in dotfile
      become: true
      lineinfile:
        path: ~{{ ansible_user }}/.bashrc
        regexp: "^export VAULT_CACERT="
        line: "export VAULT_CACERT=/etc/vault/tls/vault-ca.crt"
        owner: "{{ ansible_user }}"
        create: true
        mode: 0644
