---
dependency:
  name: galaxy
lint: |
  set -e
  yamllint .
  ansible-lint
driver:
  name: docker
platforms:
  - name: vault.ricsanfre.com
    image: "ricsanfre/docker-${MOLECULE_DISTRO:-ubuntu}-ansible:${MOLECULE_RELEASE:-latest}"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    privileged: true
    pre_build_image: true
    exposed_ports:
      - 8200/tcp
      - 8201/tcp
    published_ports:
      - 0.0.0.0:8200:8200/tcp
      - 0.0.0.0:8201:8201/tcp
    env:
      http_proxy: http://10.201.0.1:4567
      https_proxy: http://10.201.0.1:4567
provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
verifier:
  name: ansible
